### PR TITLE
Add Coineus token

### PR DESCRIPTION
**Pull request by CryptoJoshua**

### CODE REVIEW

**Comment by CryptoJoshua** [comment]
@t0mcr8se @mul53 @leonprou

**Comment by t0mcr8se** [comment]
Hey @CryptoJoshua can you please run yarn build and increment the version in package.json and build/voltage-swap-default.tokenlist.json to 1.4.0 ?

**Comment by CryptoJoshua** [comment]
@t0mcr8se Done

**Review by t0mcr8se — APPROVED** [review]
lgtm!

**Pull request merged**
